### ISSUE TITLE
Instructions for running Cascalog on Windows (at least 7+) without Hadoop

### ISSUE THREAD

**Issue by atishlahiri** [nathanmarz/cascalog#136]
It would be very helpful to have instructions on how to run Cascalog on Windows 7+ without Hadoop to do non-Big Data tasks like data munging. This would help many of us who are interested in learning Cascalog but have Windows desktops at work, to do ad hoc data analysis and other tasks using Cascalog and thus get familiar with it. It would definitely help in disseminating Cascalog. 

Best wishes to the Cascalog Team!

**Comment by sritchie** [comment]
@atishlahiri would love some help on this on the doc site!
