### ISSUE TITLE
Create ElasticSearch module using ESTap

### ISSUE THREAD

**Issue by sritchie** [nathanmarz/cascalog#189]
Looks straightforward:

https://github.com/elasticsearch/elasticsearch-hadoop/blob/master/src/main/java/org/elasticsearch/hadoop/cascading/ESTap.java

**Comment by sritchie** [comment]
@alexrobbins hey! Do you guys still need this? Just looking through issues and cleaning stuff up.

**Comment by alexrobbins** [comment]
No, we ended up writing into elasticsearch from a vanilla hadoop job so we didn't need this.
