### ISSUE TITLE
Negate not working?

### ISSUE THREAD

**Issue by amanas** [nathanmarz/cascalog#236]
Please, can you make this to happen?

(fact
  "What!"
  (<- [?a ?b ?c]
      ([["a1" "t1"]
        ["a3" "t3"]] ?a ?b)
      ([["t1" "gb"]
        ["t1" "es"]
        ["t1" "global"]
        ["t3" "es"]
        ["t3" "global"]] ?b ?c)
      ((ops/negate [["a3" "es"]]) ?a ?c)) =>
  (produces [["a1" "t1" "gb"]
                    ["a1" "t1" "es"]
                    ["a1" "t1" "global"]
                    ["a3" "t3" "es"]
                    ["a3" "t3" "global"]]))

**Comment by sritchie** [comment]
Hey, I just ran this and I get what I'd expect:

```clojure
cascalog.api> (??<- [?a ?b ?c]
      ([["a1" "t1"]
        ["a3" "t3"]] ?a ?b)
      ([["t1" "gb"]
        ["t1" "es"]
        ["t1" "global"]
        ["t3" "es"]
        ["t3" "global"]] ?b ?c)
      ((lo/negate [["a3" "es"]]) ?a ?c)) 
(["a1" "t1" "gb"] ["a1" "t1" "global"] ["a3" "t3" "global"])
```

Match every tuple where `?c` doesn't equal `"es"`. Is that what you were expecting?

**Comment by amanas** [comment]
Umm... difficult to remember what I was expecting a year ago 8)

Probably it is fine now.

Thanks sritchie.

**Comment by sritchie** [comment]
Sorry again about the delay :)

**Comment by amanas** [comment]
No please, no need to say sorry.

8)


2015-04-20 16:23 GMT+02:00 Sam Ritchie <notifications@github.com>:
