### ISSUE TITLE
ClassNotFoundException: cascalog.logic.def.ParallelAggregator

### ISSUE THREAD

**Issue by methylene** [nathanmarz/cascalog#245]
We get this compile error under certain circumstances, see here: methylene/class-not-found@11cb158d7eadfc8e6b3e5810af77e4b20cb34305

It goes away when you remove test/user.clj or the :aot and :main in project.clj. It affects cascalog 2.1.0.

**Comment by sritchie** [comment]
Hey @methylene, is this still an issue for you guys?

**Comment by sritchie** [comment]
Closing this since it looks from the README like a classloader issue. Feel free to reopen if I'm mistaken. Thanks!
