### ISSUE TITLE
bind print-level and print-depth to nil when saving the environment instead of using print-dup

### ISSUE THREAD

**Issue by hiredman** [nathanmarz/cascalog#250]
https://github.com/nathanmarz/cascalog/blob/develop/cascalog-core/src/clj/cascalog/logic/fn.clj#L13-L14

the # you are trying to avoid using *print-dup* are inserted because you have *print-level* and *print-depth* bound at the repl, if you bind those to nil you don't need *print-dup*, and print-dup should be avoided because it is not portable (it creates strings which to read properly depend on eval reader)

**Comment by sritchie** [comment]
@hiredman but don't we always have the eval reader, when deserializing these functions?

**Comment by sritchie** [comment]
@hiredman, happy to re-open this and make that change - closing for now since I don't know of a case where we won't have the eval reader. Good to know, btw.
