### ISSUE TITLE
JCascalog not working - ClassCastException when calling Api.compileFlow

### ISSUE THREAD

**Issue by dkincaid** [nathanmarz/cascalog#261]
When calling Api.compileFlow the object returned is a ClojureFlow Clojure record instead of a Cascading Flow object so a ClassCastException is thrown.

     java.lang.ClassCastException: cascalog.cascading.types.ClojureFlow cannot be cast to cascading.flow.Flow
    at jcascalog.Api.compileFlow(Api.java:26)
    at jcascalog.Api.compileFlow(Api.java:34)

**Comment by sritchie** [comment]
@dkincaid, is this all fixed with that new stuff you added?

**Comment by dkincaid** [comment]
Yes. It is! Thanks.
