### ISSUE TITLE
Add ability to name subqueries

### ISSUE THREAD

**Issue by nathanmarz** [nathanmarz/cascalog#36]
e.g., (<- [?person ?count] (follows ?person _) (c/count ?count) (:name "follows-count"))

The name should show up in the JobTracker UI.

**Comment by sritchie** [comment]
You can do this w/ Cascalog 2 now, but we still should expose it as a Cascalog option.

**Comment by sritchie** [comment]
@sorenmacbeth, do you still want this bad boy?
