### ISSUE TITLE
Queries started from non-main thread fail to resolve application jar

### ISSUE THREAD

**Issue by ipostelnik** [nathanmarz/cascalog#75]
Queries launched from non-main thread fail to resolve application jar, unless the job is packaged as an uberjar. If the job is packaged with all dependencies in lib/ sub-directory inside the jar, then cascading can't resolve application jar. 

Usually application jar is configured using FlowConnector.setApplicationJarClass. If this the app jar is not set cascading tries to resolve it on its own. If running from main thread, it will use the class of main() method, otherwise it uses the MultiMapReducePlanner class for jar discovery.

**Comment by sritchie** [comment]
@ipostelnik did you ever figure out how to get around this? Any thoughts on how we can fix this?

**Comment by ipostelnik** [comment]
IIRC, this was related to cascalog-checkpoint. We had stopped using it, do
I haven't seen this issue. Cascading has a way to put jar name into
properties, users can always do this instead.

**Comment by sritchie** [comment]
Gotcha.
